"""CLI rendering helpers."""

from sideclaw.cli.render.console import get_console, print_line, prompt_input
from sideclaw.cli.render.formatting import (
    build_agent_header_lines,
    build_clarify_lines,
    format_browser_status,
    format_created_file_line,
    format_cron_row,
    format_cron_summary,
    format_cron_timestamp,
    format_error_message,
    format_exit_message,
    format_gateway_channels_line,
    format_gateway_header,
    format_gateway_model_line,
    format_heading,
    format_image_generation_status,
    format_provider_key_status,
    format_session_count,
    format_session_reset_message,
    format_shell_exec_status,
    format_success_message,
    format_telegram_status,
    format_tts_status,
    format_warning_message,
    format_web_search_status,
    render_agent_markdown,
)

__all__ = [
    "build_agent_header_lines",
    "build_clarify_lines",
    "format_browser_status",
    "format_created_file_line",
    "format_cron_row",
    "format_cron_summary",
    "format_cron_timestamp",
    "format_error_message",
    "format_exit_message",
    "format_gateway_channels_line",
    "format_gateway_header",
    "format_gateway_model_line",
    "format_heading",
    "format_image_generation_status",
    "format_provider_key_status",
    "format_session_count",
    "format_session_reset_message",
    "format_shell_exec_status",
    "format_success_message",
    "format_telegram_status",
    "format_tts_status",
    "format_warning_message",
    "format_web_search_status",
    "get_console",
    "print_line",
    "prompt_input",
    "render_agent_markdown",
]
